name: AlexVineyard
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47972
title: Alex Vineyard
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11067818384617567
  lightness: 0.43580061849206686
  saturation: 0.24008268327452242
  rhythmicContrast: 0.13601050223223865
purpose: []
